services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80  
    volumes:
      - ./flask-app/static/:/usr/share/nginx/html/static/
      - ./flask-app/templates/index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["python", "app.py"]
    ports:
      - 5000:5000
    volumes:
      - app:/app
    depends_on:
      - es
  es:
    image: elasticsearch:7.17.13
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
  app:
  nginx.conf: